# Generated by Django 5.1.4 on 2025-01-16 15:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('room_type', models.CharField(choices=[('Single', 'Single Room'), ('Double', 'Double Room'), ('Ensuite', 'Ensuite Room'), ('Studio', 'Studio')], default='Single', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('minimum_stay', models.IntegerField(default=1, help_text='Minimum stay in months', validators=[django.core.validators.MinValueValidator(1)])),
                ('bills_included', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Listing',
                'verbose_name_plural': 'Room Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
