# Generated by Django 5.1.4 on 2025-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities', null=True),
        ),
    ]
