# Generated by Django 5.1.4 on 2025-01-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_alter_savedad_ad_delete_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='user',
        ),
        migrations.CreateModel(
            name='PropertySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('search_type', models.CharField(choices=[('offered', 'Rooms for Rent'), ('wanted', 'Rooms Wanted'), ('coliving', 'CoLiving Search')], max_length=20)),
                ('property_type', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('House', 'House'), ('Studio', 'Studio')], max_length=20, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_size', models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double')], max_length=20, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Property searches',
                'ordering': ['-search_date'],
            },
        ),
        migrations.DeleteModel(
            name='SavedAd',
        ),
        migrations.DeleteModel(
            name='SavedSearch',
        ),
    ]
