# Generated by Django 5.1.4 on 2025-01-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_ad_savedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='property_type',
            field=models.TextField(blank=True, help_text='Comma-separated list of property types'),
        ),
    ]
