# Generated by Django 5.1.4 on 2025-01-28 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now, help_text='When is the room available from?'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='availability',
            field=models.CharField(blank=True, help_text='Legacy field for compatibility', max_length=10, null=True),
        ),
    ]
