# Generated by Django 5.1.4 on 2025-01-26 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlisting',
            name='ages',
            field=models.CharField(default='18-99', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='availability',
            field=models.CharField(default='Immediately', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='balcony',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='bills_included',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='broadband',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='couples_ok',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='current_household',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='description',
            field=models.TextField(default='Room description not provided'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='disabled_access',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='furnishings',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='garden',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='gender',
            field=models.CharField(default='Any', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='living_room',
            field=models.CharField(choices=[('shared', 'Shared'), ('private', 'Private')], default='shared', max_length=7),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='location',
            field=models.CharField(default='Location not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='max_age',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='maximum_term',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='minimum_term',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='occupation',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='occupation_preference',
            field=models.CharField(default='Any', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='parking',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='pets',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='pets_ok',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='postcode',
            field=models.CharField(default='Not specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='references_required',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='size',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='smoker',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='smoking_ok',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='title',
            field=models.CharField(default='Room Available', max_length=200),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
