# Generated by Django 5.1.4 on 2025-01-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='amenities',
            field=models.TextField(blank=True, help_text="Comma-separated list of amenities (e.g., 'WiFi, Parking, Pool')", null=True),
        ),
    ]
