# Generated by Django 5.1.4 on 2025-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_roomlisting_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlisting',
            name='size',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('single', 'single'), ('double', 'double')], default='Single', max_length=50),
        ),
    ]
