# Generated by Django 5.1.4 on 2025-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_roomlisting_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='search_type',
            field=models.CharField(choices=[('offered', 'Rooms for Rent'), ('wanted', 'Rooms Wanted'), ('coliving', 'CoLiving')], default='offered', max_length=20),
        ),
    ]
