# Generated by Django 5.1.4 on 2025-01-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_roomlisting_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
