# Generated by Django 5.1.4 on 2025-01-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_roomlisting_search_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlisting',
            name='postcode',
            field=models.CharField(default='Not specified', max_length=20),
        ),
    ]
