# Generated by Django 5.1.4 on 2025-01-27 12:49

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_roomlisting_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='availability',
            field=models.CharField(max_length=100, default='Immediately'),
        ),
    ]
