# Generated by Django 5.1.4 on 2025-01-27 12:59
from django.db import migrations, models
from django.core.validators import MinValueValidator

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_availability_field'),
    ]

    operations = [
        # Room Details
        migrations.AddField(
            model_name='roomlisting',
            name='maximum_term',
            field=models.IntegerField(null=True, blank=True, default=12),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='deposit',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0.00),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='furnishings',
            field=models.CharField(max_length=255, default="Not specified"),
        ),

        # Property Features
        migrations.AddField(
            model_name='roomlisting',
            name='parking',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='garden',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='balcony',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='disabled_access',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='living_room',
            field=models.CharField(max_length=7, choices=[('shared', 'Shared'), ('private', 'Private')], default='shared'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='broadband',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),

        # Household Details
        migrations.AddField(
            model_name='roomlisting',
            name='current_household',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='ages',
            field=models.CharField(max_length=100, default="18-99"),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='smoker',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='pets',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='occupation',
            field=models.CharField(max_length=100, default="Not specified"),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='gender',
            field=models.CharField(max_length=50, default="Any"),
        ),

        # Preferences
        migrations.AddField(
            model_name='roomlisting',
            name='couples_ok',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='smoking_ok',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='pets_ok',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='occupation_preference',
            field=models.CharField(max_length=100, default="Any"),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='references_required',
            field=models.CharField(max_length=3, choices=[('yes', 'Yes'), ('no', 'No')], default='yes'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='max_age',
            field=models.IntegerField(default=99),
        ),
    ]