# Generated by Django 5.1.4 on 2025-01-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test_field',
        ),
    ]
